// Generated by hand for v0.1. Replace with `supabase gen types` later.

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: { id: string; name: string | null; default_currency: string; created_at: string };
        Insert: { id: string; name?: string | null; default_currency?: string };
        Update: { name?: string | null; default_currency?: string };
      };
      groups: {
        Row: { id: string; name: string; icon: string | null; color: string | null; created_by: string; created_at: string };
        Insert: { id?: string; name: string; icon?: string | null; color?: string | null; created_by: string };
        Update: { name?: string; icon?: string | null; color?: string | null };
      };
      group_members: {
        Row: { group_id: string; user_id: string; joined_at: string };
        Insert: { group_id: string; user_id: string };
        Update: never;
      };
      friends: {
        Row: { user_id: string; friend_user_id: string; created_at: string };
        Insert: { user_id: string; friend_user_id: string };
        Update: never;
      };
      expenses: {
        Row: {
          id: string;
          group_id: string | null;
          paid_by: string;
          amount_cents: number;
          currency: string;
          description: string;
          category: string | null;
          tags: string[] | null;
          occurred_at: string;
          created_by: string;
          created_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          group_id?: string | null;
          paid_by: string;
          amount_cents: number;
          currency: string;
          description: string;
          category?: string | null;
          tags?: string[] | null;
          occurred_at?: string;
          created_by: string;
        };
        Update: Partial<{
          group_id: string | null;
          paid_by: string;
          amount_cents: number;
          currency: string;
          description: string;
          category: string | null;
          tags: string[] | null;
          occurred_at: string;
          deleted_at: string | null;
        }>;
      };
      splits: {
        Row: { expense_id: string; user_id: string; share_cents: number; share_type: string; share_value: number };
        Insert: { expense_id: string; user_id: string; share_cents: number; share_type: string; share_value: number };
        Update: never;
      };
      payments: {
        Row: {
          id: string;
          from_user: string;
          to_user: string;
          amount_cents: number;
          currency: string;
          note: string | null;
          occurred_at: string;
          group_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          from_user: string;
          to_user: string;
          amount_cents: number;
          currency: string;
          note?: string | null;
          occurred_at?: string;
          group_id?: string | null;
        };
        Update: Partial<{ note: string | null }>;
      };
      comments: {
        Row: { id: string; expense_id: string; author: string; body: string; created_at: string };
        Insert: { id?: string; expense_id: string; author: string; body: string };
        Update: { body?: string };
      };
    };
  };
};
